version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8765:8765"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8888:80"
    depends_on:
      - backend
    networks:
      - app-network

  recommender:
    build:
      context: .
      dockerfile: Dockerfile.recommender
    ports:
      - "8766:80"
    depends_on:
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
